Experiment_name: bone_27_2_finetune

# feeder
feeder: feeders.feeder.Feeder
train_feeder_args:
  data_path: /home/perceive/slr/rgbd/data/val_gendata/27/val_data_bone.npy
  label_path: /home/perceive/slr/rgbd/data/val_gendata/27/val_label.pkl
  debug: False
  random_choose: True
  random_shift: True
  window_size: 100
  normalization: True
  random_mirror: True
  random_mirror_p: 0.5
  is_vector: True

test_feeder_args:
  data_path: /home/perceive/slr/rgbd/data/test_gendata/27/test_data_bone.npy
  label_path: /home/perceive/slr/rgbd/data/test_gendata/27/test_label.pkl
  random_mirror: False
  normalization: True
  is_vector: True

# model
model: model.decouple_gcn_attn.Model
model_args:
  num_class: 156 # 226
  num_point: 27
  num_person: 1
  graph: graph.sign_27.Graph
  groups: 16
  block_size: 41
  graph_args:
    labeling_mode: 'spatial'

#optim
weight_decay: 0.0001
base_lr: 0.01
step: [50]

# training
device: [0]
weights: /home/perceive/slr/rgbd/CVPR21Chal-SLR/SL-GCN/save_models/train/sign_bone_final-24.pt
keep_rate: 0.9
only_train_epoch: 1
batch_size: 64
test_batch_size: 64
num_epoch: 100
nesterov: True
warm_up_epoch: 0